name: Android CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace --no-daemon
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ThemeTool-release
          path: "app/build/outputs/apk/release/*.apk"