name: Android CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          bash ./gradlew assemble
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ThemeTool-release.apk
          path: ./app/build/outputs/apk/release

      - name: Upload to Telegram via curl
        run: APK_PATH="./app/build/outputs/apk/release/ThemeTool-release.apk"

        COMMIT_MESSAGE="Commit message: \`${{ github.event.head_commit.message }}\`"
          
          ESCAPED_MESSAGE=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''${COMMIT_MESSAGE}'''))")
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
          -F chat_id="${{ secrets.TELEGRAM_CHANNEL_ID }}" \
          -F disable_web_page_preview=true \
          -F parse_mode="Markdown" \
          -F caption="${COMMIT_MESSAGE}" \
          -F document=@"$APK_PATH"
