name: Android CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks
        shell: bash

      - name: Build Signed APK
        run: ./gradlew assembleRelease --stacktrace --no-daemon
        env:
          KEYSTORE_PATH: "${{ github.workspace }}/keystore.jks"
          KEYSTORE_PASS: "${{ secrets.KEY_STORE_PASSWORD }}"
          KEY_ALIAS: "${{ secrets.ALIAS }}"
          KEY_PASSWORD: "${{ secrets.KEY_PASSWORD }}"

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ThemeTool-release
          path: app/build/outputs/apk/release/*.apk